const ActionTypes = {
  UPDATE_EMPLOYEES: "UPDATE_EMPLOYEES",
  CHANGE_DEPARTMENT: 'CHANGE_DEPARTMENT',
  RAISE_SALARY: 'RAISE_SALARY',
  BACKGROUND_COLOR_CHANGE: "BACKGROUND_COLOR_CHANGE"
};

export default ActionTypes;
